"""
Contains helper classes.
"""

# pylint: disable=invalid-name
# pylint: disable=too-few-public-methods

from enum import Enum


class MeaningCategory(Enum):
    """Enumeration class that contains meaning category values."""
    ALL = 0
    HUMAN_ALL = 1
    HUMAN_TYPES_OF_PEOPLE = 2
    HUMAN_BODY_PARTS = 3
    HUMAN_HEALTH_STATUS = 4
    HUMAN_PHYSIOLOGICAL_PHENOMENA = 5
    HUMAN_SENSES = 6
    HUMAN_EMOTION = 7
    HUMAN_PERSONALITY = 8
    HUMAN_ATTITUDE = 9
    HUMAN_FEATURES = 10
    HUMAN_ABILITY = 11
    HUMAN_PHYSICAL_CHANGES = 12
    HUMAN_PHYSICAL_ACTIVITIES = 13
    HUMAN_ACTIONS_DONE_TO_THE_BODY = 14
    HUMAN_COGNITIVE_BEHAVIOR = 15
    HUMAN_SOUND = 16
    HUMAN_INNER_PARTS_OF_THE_BODY = 17
    LIFE_ALL = 18
    LIFE_STATE_OF_BEING = 19
    LIFE_LIFE_ACTIVIES = 20
    LIFE_DAILY_ACTIVITIES = 21
    LIFE_KINSHIP = 22
    LIFE_FAMILY_EVENTS = 23
    LIFE_LEISURE_TOOLS = 24
    LIFE_LEISURE_FACILITIES = 25
    LIFE_LEISURE_ACTIVITIES = 26
    LIFE_DISEASES_AND_SYMPTOMS = 27
    LIFE_MEDICAL_ACTIVITIES = 28
    LIFE_MEDICAL_FACILITIES = 29
    LIFE_MEDICINE = 30
    DIETARY_ALL = 31
    DIETARY_FOOD_TYPES = 32
    DIETARY_VEGETABLES = 33
    DIETARY_GRAIN = 34
    DIETARY_FRUIT = 35
    DIETARY_BEVERAGES = 36
    DIETARY_FOOD_INGREDIENTS = 37
    DIETARY_COOKING_APPLIANCES = 38
    DIETARY_EATING_PLACES = 39
    DIETARY_TASTE = 40
    DIETARY_EATING_AND_COOKING_ACTIVITIES = 41
    CLOTHING_ALL = 42
    CLOTHING_TYPES_OF_CLOTHING = 43
    CLOTHING_FABRIC = 44
    CLOTHING_PARTS_OF_CLOTHING = 45
    CLOTHING_HATS_SHOES_ACCESSORIES = 46
    CLOTHING_PLACES_RELATED_TO_CLOTHING = 47
    CLOTHING_STATE_OF_CLOTHING = 48
    CLOTHING_ACTIVITIES_RELATED_TO_CLOTHING = 49
    CLOTHING_BEAUTY_AND_HEALTH = 50
    HOME_LIFE_ALL = 51
    HOME_LIFE_BUILDING_TYPES = 52
    HOME_LIFE_TYPE_OF_HOUSING = 53
    HOME_LIFE_RESIDENTIAL_AREA = 54
    HOME_LIFE_HOUSEHOLD_ITEMS = 55
    HOME_LIFE_HOUSING_STRUCTURE = 56
    HOME_LIFE_RESIDENTIAL_STATUS = 57
    HOME_LIFE_RESIDENTIAL_ACTIVITIES = 58
    HOME_LIFE_RESIDENTIAL_CHORES = 59
    SOCIAL_LIFE_ALL = 60
    SOCIAL_LIFE_HUMAN_RELATIONSHIPS = 61
    SOCIAL_LIFE_MEANS_OF_COMMUNICATION = 62
    SOCIAL_LIFE_MODES_OF_TRANSPORTATION = 63
    SOCIAL_LIFE_PLACES_FOR_TRANSPORTATION_USAGE = 64
    SOCIAL_LIFE_MEDIA = 65
    SOCIAL_LIFE_WORKPLACE = 66
    SOCIAL_LIFE_TITLES_AND_POSITIONS = 67
    SOCIAL_LIFE_OCCUPATION = 68
    SOCIAL_LIFE_SOCIAL_EVENTS = 69
    SOCIAL_LIFE_SOCIAL_LIFE_STATUS = 70
    SOCIAL_LIFE_SOCIAL_ACTIVITIES = 71
    SOCIAL_LIFE_TRANSPORTATION_USAGE = 72
    SOCIAL_LIFE_WORKPLACE_LIFE = 73
    SOCIAL_LIFE_LANGUAGE_ACTIVITIES = 74
    SOCIAL_LIFE_COMMUNICATION_ACTIVITIES = 75
    SOCIAL_LIFE_GRAMMAR_AND_SPEECH = 76
    ECONOMIC_ALL = 77
    ECONOMIC_PEOPLE = 78
    ECONOMIC_PLACES = 79
    ECONOMIC_MEANS = 80
    ECONOMIC_PRODUCTS = 81
    ECONOMIC_STATUS = 82
    ECONOMIC_ACTIVITIES = 83
    EDUCATION_ALL = 84
    EDUCATION_PEOPLE = 85
    EDUCATION_MAJORS_AND_SUBJECTS = 86
    EDUCATION_EDUCATIONAL_INSTITUTIONS = 87
    EDUCATION_SCHOOL_FACILITIES = 88
    EDUCATION_OBJECTS = 89
    EDUCATION_ACADEMIC_TERMS = 90
    EDUCATION_TEACHING_AND_LEARNING_ACTIVITIES = 91
    EDUCATION_ACADEMIC_ACTIVITIES = 92
    RELIGION_ALL = 93
    RELIGION_TYPES_OF_RELIGION = 94
    RELIGION_PLACES = 95
    RELIGION_PEOPLE = 96
    RELIGION_RELIGIOUS_WORDS = 97
    RELIGION_MAJOR_FIGURES = 98
    RELIGION_OBJECTS = 99
    RELIGION_PRACTICES = 100
    CULTURE_ALL = 101
    CULTURE_CULTURAL_ACTIVITY_PARTICIPANTS = 102
    CULTURE_MUSIC = 103
    CULTURE_FINE_ART = 104
    CULTURE_LITERATURE = 105
    CULTURE_ART = 106
    CULTURE_POP_CULTURE = 107
    CULTURE_TRADITIONAL_CULTURE = 108
    CULTURE_CULTURAL_ACTIVITY_PLACES = 109
    CULTURE_CULTURAL_ACTIVITIES = 110
    POLITICS_AND_ADMINISTRATION_ALL = 111
    POLITICS_AND_ADMINISTRATION_PUBLIC_INSTITUTIONS = 112
    POLITICS_AND_ADMINISTRATION_JUDICIAL_AND_SECURITY_PERSONNEL = 113
    POLITICS_AND_ADMINISTRATION_WEAPONS = 114
    POLITICS_AND_ADMINISTRATION_POLITICS_AND_SECURITY = 115
    POLITICS_AND_ADMINISTRATION_POLITICAL_ACTS = 116
    POLITICS_AND_ADMINISTRATION_LAW_AND_SECURITY_ACTS = 117
    POLITICS_AND_ADMINISTRATION_POLITICAL_AND_ADMINISTRATIVE_PERSONNEL = 118
    NATURE_ALL = 119
    NATURE_TOPOGRAPHY = 120
    NATURE_SURFACE_OBJECTS = 121
    NATURE_CELESTIAL_BODIES = 122
    NATURE_NATURAL_RESOURCES = 123
    NATURE_DISASTERS = 124
    NATURE_WEATHER_AND_CLIMATE = 125
    ANIMALS_AND_PLANTS_ALL = 126
    ANIMALS_AND_PLANTS_ANIMALS = 127
    ANIMALS_AND_PLANTS_INSECTS = 128
    ANIMALS_AND_PLANTS_PLANTS = 129
    ANIMALS_AND_PLANTS_PARTS_OF_ANIMALS = 130
    ANIMALS_AND_PLANTS_PARTS_OF_PLANTS = 131
    ANIMALS_AND_PLANTS_BEHAVIORS = 132
    ANIMALS_AND_PLANTS_SOUNDS = 133
    CONCEPTS_ALL = 134
    CONCEPTS_SHAPE = 135
    CONCEPTS_PROPERTY = 136
    CONCEPTS_SPEED = 137
    CONCEPTS_BRIGHTNESS = 138
    CONCEPTS_TEMPERATURE = 139
    CONCEPTS_COLORS = 140
    CONCEPTS_NUMBERS = 141
    CONCEPTS_COUNTERS = 142
    CONCEPTS_AMOUNT = 143
    CONCEPTS_DEGREE = 144
    CONCEPTS_ORDER = 145
    CONCEPTS_FREQUENCY = 146
    CONCEPTS_TIME = 147
    CONCEPTS_LOCATION_AND_DIRECTION = 148
    CONCEPTS_AREA = 149
    CONCEPTS_INSTRUCTIONS = 150
    CONCEPTS_CONNECTION = 151
    CONCEPTS_QUESTION_WORDS = 152
    CONCEPTS_PRONOUNS = 153

class SubjectCategory(Enum):
    """Enumeration class that contains subject category values."""
    ALL = 0
    ELEMENTARY_GREETING = 1
    ELEMENTARY_INTRODUCING_ONESELF = 2
    ELEMENTARY_INTRODUCING_FAMILY = 3
    ELEMENTARY_EXCHANGING_PERSONAL_INFORMATION = 4
    ELEMENTARY_DESCRIBING_LOCATION = 5
    ELEMENTARY_DIRECTIONS = 6
    ELEMENTARY_USING_TRANSPORTATION = 7
    ELEMENTARY_PURCHASING_GOODS = 8
    ELEMENTARY_ORDERING_FOOD = 9
    ELEMENTARY_DESCRIBING_DISHES = 10
    ELEMENTARY_EXPRESSING_TIME = 11
    ELEMENTARY_EXPRESSING_DATE = 12
    ELEMENTARY_EXPRESSING_DAY_OF_THE_WEEK = 13
    ELEMENTARY_WEATHER_AND_SEASON = 14
    ELEMENTARY_DAILY_LIFE = 15
    ELEMENTARY_SCHOOL_LIFE = 16
    ELEMENTARY_LIFE_IN_KOREA = 17
    ELEMENTARY_MAKING_PROMISES = 18
    ELEMENTARY_MAKING_PHONE_CALLS = 19
    ELEMENTARY_EXPRESSING_GRATITUDE = 20
    ELEMENTARY_APOLOGIZING = 21
    ELEMENTARY_TRAVEL = 22
    ELEMENTARY_WEEKENDS_AND_HOLIDAYS = 23
    ELEMENTARY_HOBBIES = 24
    ELEMENTARY_FAMILY_EVENTS = 25
    ELEMENTARY_HEALTH = 26
    ELEMENTARY_USING_THE_HOSPITAL = 27
    ELEMENTARY_USING_THE_PHARMACY = 28
    ELEMENTARY_USING_THE_LIBRARY = 29
    ELEMENTARY_USING_THE_POST_OFFICE = 30
    ELEMENTARY_USING_THE_IMMIGRATION_OFFICE = 31
    ELEMENTARY_INVITING_AND_VISITING = 32
    ELEMENTARY_FINDING_A_HOUSE = 33
    ELEMENTARY_HOUSEWORK = 34
    ELEMENTARY_EXPRESSING_EMOTIONS = 35
    ELEMENTARY_DESCRIBING_PERSONALITY = 36
    ELEMENTARY_DESCRIBING_CLOTHES = 37
    ELEMENTARY_DESCRIBING_PHYSICAL_FEATURES = 38
    ELEMENTARY_WATCHING_MOVIES = 39
    INTERMEDIATE_EXCHANGING_PERSONAL_INFORMATION = 40
    INTERMEDIATE_USING_TRANSPORTATION = 41
    INTERMEDIATE_GEOLOGICAL_INFORMATION = 42
    INTERMEDIATE_PURCHASING_GOODS = 43
    INTERMEDIATE_DESCRIBING_FOOD = 44
    INTERMEDIATE_DESCRIBING_DISHES = 45
    INTERMEDIATE_WEATHER_AND_SEASON = 46
    INTERMEDIATE_SCHOOL_LIFE = 47
    INTERMEDIATE_LIFE_IN_KOREA = 48
    INTERMEDIATE_JOBS_AND_CAREERS = 49
    INTERMEDIATE_WORKPLACE_LIFE = 50
    INTERMEDIATE_TRAVEL = 51
    INTERMEDIATE_WEEKENDS_AND_HOLIDAYS = 52
    INTERMEDIATE_HOBBIES = 53
    INTERMEDIATE_FAMILY_EVENTS = 54
    INTERMEDIATE_FAMILY_EVENTS_DURING_HOLIDAYS = 55
    INTERMEDIATE_HEALTH = 56
    INTERMEDIATE_USING_PUBLIC_INSTITUTIONS = 57
    INTERMEDIATE_INVITING_AND_VISITING = 58
    INTERMEDIATE_FINDING_A_HOUSE = 59
    INTERMEDIATE_HOUSEWORK = 60
    INTERMEDIATE_EXPRESSING_EMOTIONS = 61
    INTERMEDIATE_DESCRIBING_PERSONALITY = 62
    INTERMEDIATE_DESCRIBING_CLOTHES = 63
    INTERMEDIATE_DESCRIBING_PHYSICAL_FEATURES = 64
    INTERMEDIATE_PERFORMANCES_AND_APPRECIATION = 65
    INTERMEDIATE_MASS_MEDIA = 66
    INTERMEDIATE_COMPUTERS_AND_THE_INTERNET = 67
    INTERMEDIATE_DESCRIBING_EVENTS_AND_DISASTERS = 68
    INTERMEDIATE_ENVIRONMENTAL_ISSUES = 69
    INTERMEDIATE_COMPARING_CULTURES = 70
    INTERMEDIATE_HUMAN_RELATIONSHIPS = 71
    INTERMEDIATE_KOREAN_LITERATURE = 72
    INTERMEDIATE_SOLVING_PROBLEMS = 73
    INTERMEDIATE_TALKING_ABOUT_MISTAKES = 74
    INTERMEDIATE_DATING_AND_MARRIAGE = 75
    INTERMEDIATE_LANGUAGE = 76
    ADVANCED_GEOLOGICAL_INFORMATION = 77
    ADVANCED_ECONOMICS_AND_ADMINISTRATION = 78
    ADVANCED_DIETARY_CULTURE = 79
    ADVANCED_CLIMATE = 80
    ADVANCED_EDUCATION = 81
    ADVANCED_JOBS_AND_CAREERS = 82
    ADVANCED_WORKPLACE_LIFE = 83
    ADVANCED_HOBBIES = 84
    ADVANCED_HEALTH_AND_MEDICAL_TREATMENT = 85
    ADVANCED_RESIDENTIAL_AREA = 86
    ADVANCED_PSYCHOLOGY = 87
    ADVANCED_APPEARANCE = 88
    ADVANCED_POP_CULTURE = 89
    ADVANCED_COMPUTERS_AND_THE_INTERNET = 90
    ADVANCED_SOCIAL_ISSUES = 91
    ADVANCED_ENVIRONMENTAL_ISSUES = 92
    ADVANCED_SOCIAL_SYSTEM = 93
    ADVANCED_CULTURAL_DIFFERENCES = 94
    ADVANCED_HUMAN_RELATIONSHIPS = 95
    ADVANCED_ART = 96
    ADVANCED_ARCHITECTURE = 97
    ADVANCED_SCIENCE_AND_TECHNOLOGY = 98
    ADVANCED_LAW = 99
    ADVANCED_SPORTS = 100
    ADVANCED_PRESS = 101
    ADVANCED_LANGUAGE = 102
    ADVANCED_HISTORY = 103
    ADVANCED_POLITICS = 104
    ADVANCED_RELIGION = 105
    ADVANCED_PHILOSOPHY_AND_ETHICS = 106


class MeaningCategoryHelper:
    """Helper class for meaning categories."""

    def __new__(cls, value):
        return MeaningCategory(value)

    @staticmethod
    def enum():
        """Returns the underlying enumeration type."""
        return MeaningCategory

    ALL = MeaningCategory.ALL

    class HUMAN:
        """Helper class for human meaning categories."""
        ALL = MeaningCategory.HUMAN_ALL
        TYPES_OF_PEOPLE = MeaningCategory.HUMAN_TYPES_OF_PEOPLE
        BODY_PARTS = MeaningCategory.HUMAN_BODY_PARTS
        HEALTH_STATUS = MeaningCategory.HUMAN_HEALTH_STATUS
        PHYSIOLOGICAL_PHENOMENA = MeaningCategory.HUMAN_PHYSIOLOGICAL_PHENOMENA
        SENSES = MeaningCategory.HUMAN_SENSES
        EMOTION = MeaningCategory.HUMAN_EMOTION
        PERSONALITY = MeaningCategory.HUMAN_PERSONALITY
        ATTITUDE = MeaningCategory.HUMAN_ATTITUDE
        FEATURES = MeaningCategory.HUMAN_FEATURES
        ABILITY = MeaningCategory.HUMAN_ABILITY
        PHYSICAL_CHANGES = MeaningCategory.HUMAN_PHYSICAL_CHANGES
        PHYSICAL_ACTIVITIES = MeaningCategory.HUMAN_PHYSICAL_ACTIVITIES
        ACTIONS_DONE_TO_THE_BODY = MeaningCategory.HUMAN_ACTIONS_DONE_TO_THE_BODY
        COGNITIVE_BEHAVIOR = MeaningCategory.HUMAN_COGNITIVE_BEHAVIOR
        SOUND = MeaningCategory.HUMAN_SOUND
        INNER_PARTS_OF_THE_BODY = MeaningCategory.HUMAN_INNER_PARTS_OF_THE_BODY

    class LIFE:
        """Helper class for life meaning categories."""
        ALL = MeaningCategory.LIFE_ALL
        STATE_OF_BEING = MeaningCategory.LIFE_STATE_OF_BEING
        LIFE_ACTIVIES = MeaningCategory.LIFE_LIFE_ACTIVIES
        DAILY_ACTIVITIES = MeaningCategory.LIFE_DAILY_ACTIVITIES
        KINSHIP = MeaningCategory.LIFE_KINSHIP
        FAMILY_EVENTS = MeaningCategory.LIFE_FAMILY_EVENTS
        LEISURE_TOOLS = MeaningCategory.LIFE_LEISURE_TOOLS
        LEISURE_FACILITIES = MeaningCategory.LIFE_LEISURE_FACILITIES
        LEISURE_ACTIVITIES = MeaningCategory.LIFE_LEISURE_ACTIVITIES
        DISEASES_AND_SYMPTOMS = MeaningCategory.LIFE_DISEASES_AND_SYMPTOMS
        MEDICAL_ACTIVITIES = MeaningCategory.LIFE_MEDICAL_ACTIVITIES
        MEDICAL_FACILITIES = MeaningCategory.LIFE_MEDICAL_FACILITIES
        MEDICINE = MeaningCategory.LIFE_MEDICINE

    class DIETARY:
        """Helper class for dietary meaning categories."""
        ALL = MeaningCategory.DIETARY_ALL
        FOOD_TYPES = MeaningCategory.DIETARY_FOOD_TYPES
        VEGETABLES = MeaningCategory.DIETARY_VEGETABLES
        GRAIN = MeaningCategory.DIETARY_GRAIN
        FRUIT = MeaningCategory.DIETARY_FRUIT
        BEVERAGES = MeaningCategory.DIETARY_BEVERAGES
        FOOD_INGREDIENTS = MeaningCategory.DIETARY_FOOD_INGREDIENTS
        COOKING_APPLIANCES = MeaningCategory.DIETARY_COOKING_APPLIANCES
        EATING_PLACES = MeaningCategory.DIETARY_EATING_PLACES
        TASTE = MeaningCategory.DIETARY_TASTE
        EATING_AND_COOKING_ACTIVITIES = MeaningCategory.DIETARY_EATING_AND_COOKING_ACTIVITIES

    class CLOTHING:
        """Helper class for clothing meaning categories."""
        ALL = MeaningCategory.CLOTHING_ALL
        TYPES_OF_CLOTHING = MeaningCategory.CLOTHING_TYPES_OF_CLOTHING
        FABRIC = MeaningCategory.CLOTHING_FABRIC
        PARTS_OF_CLOTHING = MeaningCategory.CLOTHING_PARTS_OF_CLOTHING
        HATS_SHOES_ACCESSORIES = MeaningCategory.CLOTHING_HATS_SHOES_ACCESSORIES
        PLACES_RELATED_TO_CLOTHING = MeaningCategory.CLOTHING_PLACES_RELATED_TO_CLOTHING
        STATE_OF_CLOTHING = MeaningCategory.CLOTHING_STATE_OF_CLOTHING
        ACTIVITIES_RELATED_TO_CLOTHING = MeaningCategory.CLOTHING_ACTIVITIES_RELATED_TO_CLOTHING
        BEAUTY_AND_HEALTH = MeaningCategory.CLOTHING_BEAUTY_AND_HEALTH

    class HOME_LIFE:
        """Helper class for home life meaning categories."""
        ALL = MeaningCategory.HOME_LIFE_ALL
        BUILDING_TYPES = MeaningCategory.HOME_LIFE_BUILDING_TYPES
        TYPE_OF_HOUSING = MeaningCategory.HOME_LIFE_TYPE_OF_HOUSING
        RESIDENTIAL_AREA = MeaningCategory.HOME_LIFE_RESIDENTIAL_AREA
        HOUSEHOLD_ITEMS = MeaningCategory.HOME_LIFE_HOUSEHOLD_ITEMS
        HOUSING_STRUCTURE = MeaningCategory.HOME_LIFE_HOUSING_STRUCTURE
        RESIDENTIAL_STATUS = MeaningCategory.HOME_LIFE_RESIDENTIAL_STATUS
        RESIDENTIAL_ACTIVITIES = MeaningCategory.HOME_LIFE_RESIDENTIAL_ACTIVITIES
        RESIDENTIAL_CHORES = MeaningCategory.HOME_LIFE_RESIDENTIAL_CHORES

    class SOCIAL_LIFE:
        """Helper class for social life meaning categories."""
        ALL = MeaningCategory.SOCIAL_LIFE_ALL
        HUMAN_RELATIONSHIPS = MeaningCategory.SOCIAL_LIFE_HUMAN_RELATIONSHIPS
        MEANS_OF_COMMUNICATION = MeaningCategory.SOCIAL_LIFE_MEANS_OF_COMMUNICATION
        MODES_OF_TRANSPORTATION = MeaningCategory.SOCIAL_LIFE_MODES_OF_TRANSPORTATION
        PLACES_FOR_TRANSPORTATION_USAGE = \
            MeaningCategory.SOCIAL_LIFE_PLACES_FOR_TRANSPORTATION_USAGE
        MEDIA = MeaningCategory.SOCIAL_LIFE_MEDIA
        WORKPLACE = MeaningCategory.SOCIAL_LIFE_WORKPLACE
        TITLES_AND_POSITIONS = MeaningCategory.SOCIAL_LIFE_TITLES_AND_POSITIONS
        OCCUPATION = MeaningCategory.SOCIAL_LIFE_OCCUPATION
        SOCIAL_EVENTS = MeaningCategory.SOCIAL_LIFE_SOCIAL_EVENTS
        SOCIAL_LIFE_STATUS = MeaningCategory.SOCIAL_LIFE_SOCIAL_LIFE_STATUS
        SOCIAL_ACTIVITIES = MeaningCategory.SOCIAL_LIFE_SOCIAL_ACTIVITIES
        TRANSPORTATION_USAGE = MeaningCategory.SOCIAL_LIFE_TRANSPORTATION_USAGE
        WORKPLACE_LIFE = MeaningCategory.SOCIAL_LIFE_WORKPLACE_LIFE
        LANGUAGE_ACTIVITIES = MeaningCategory.SOCIAL_LIFE_LANGUAGE_ACTIVITIES
        COMMUNICATION_ACTIVITIES = MeaningCategory.SOCIAL_LIFE_COMMUNICATION_ACTIVITIES
        GRAMMAR_AND_SPEECH = MeaningCategory.SOCIAL_LIFE_GRAMMAR_AND_SPEECH

    class ECONOMIC:
        """Helper class for economic meaning categories."""
        ALL = MeaningCategory.ECONOMIC_ALL
        PEOPLE = MeaningCategory.ECONOMIC_PEOPLE
        PLACES = MeaningCategory.ECONOMIC_PLACES
        MEANS = MeaningCategory.ECONOMIC_MEANS
        PRODUCTS = MeaningCategory.ECONOMIC_PRODUCTS
        STATUS = MeaningCategory.ECONOMIC_STATUS
        ACTIVITIES = MeaningCategory.ECONOMIC_ACTIVITIES

    class EDUCATION:
        """Helper class for education meaning categories."""
        ALL = MeaningCategory.EDUCATION_ALL
        PEOPLE = MeaningCategory.EDUCATION_PEOPLE
        MAJORS_AND_SUBJECTS = MeaningCategory.EDUCATION_MAJORS_AND_SUBJECTS
        EDUCATIONAL_INSTITUTIONS = MeaningCategory.EDUCATION_EDUCATIONAL_INSTITUTIONS
        SCHOOL_FACILITIES = MeaningCategory.EDUCATION_SCHOOL_FACILITIES
        OBJECTS = MeaningCategory.EDUCATION_OBJECTS
        ACADEMIC_TERMS = MeaningCategory.EDUCATION_ACADEMIC_TERMS
        TEACHING_AND_LEARNING_ACTIVITIES = \
            MeaningCategory.EDUCATION_TEACHING_AND_LEARNING_ACTIVITIES
        ACADEMIC_ACTIVITIES = MeaningCategory.EDUCATION_ACADEMIC_ACTIVITIES

    class RELIGION:
        """Helper class for religion meaning categories."""
        ALL = MeaningCategory.RELIGION_ALL
        TYPES_OF_RELIGION = MeaningCategory.RELIGION_TYPES_OF_RELIGION
        PLACES = MeaningCategory.RELIGION_PLACES
        PEOPLE = MeaningCategory.RELIGION_PEOPLE
        RELIGIOUS_WORDS = MeaningCategory.RELIGION_RELIGIOUS_WORDS
        MAJOR_FIGURES = MeaningCategory.RELIGION_MAJOR_FIGURES
        OBJECTS = MeaningCategory.RELIGION_OBJECTS
        PRACTICES = MeaningCategory.RELIGION_PRACTICES

    class CULTURE:
        """Helper class for culture meaning categories."""
        ALL = MeaningCategory.CULTURE_ALL
        CULTURAL_ACTIVITY_PARTICIPANTS = MeaningCategory.CULTURE_CULTURAL_ACTIVITY_PARTICIPANTS
        MUSIC = MeaningCategory.CULTURE_MUSIC
        FINE_ART = MeaningCategory.CULTURE_FINE_ART
        LITERATURE = MeaningCategory.CULTURE_LITERATURE
        ART = MeaningCategory.CULTURE_ART
        POP_CULTURE = MeaningCategory.CULTURE_POP_CULTURE
        TRADITIONAL_CULTURE = MeaningCategory.CULTURE_TRADITIONAL_CULTURE
        CULTURAL_ACTIVITY_PLACES = MeaningCategory.CULTURE_CULTURAL_ACTIVITY_PLACES
        CULTURAL_ACTIVITIES = MeaningCategory.CULTURE_CULTURAL_ACTIVITIES

    class POLITICS_AND_ADMINISTRATION:
        """Helper class for politics and administration meaning categories."""
        ALL = MeaningCategory.POLITICS_AND_ADMINISTRATION_ALL
        PUBLIC_INSTITUTIONS = MeaningCategory.POLITICS_AND_ADMINISTRATION_PUBLIC_INSTITUTIONS
        JUDICIAL_AND_SECURITY_PERSONNEL = \
            MeaningCategory.POLITICS_AND_ADMINISTRATION_JUDICIAL_AND_SECURITY_PERSONNEL
        WEAPONS = MeaningCategory.POLITICS_AND_ADMINISTRATION_WEAPONS
        POLITICS_AND_SECURITY = MeaningCategory.POLITICS_AND_ADMINISTRATION_POLITICS_AND_SECURITY
        POLITICAL_ACTS = MeaningCategory.POLITICS_AND_ADMINISTRATION_POLITICAL_ACTS
        LAW_AND_SECURITY_ACTS = MeaningCategory.POLITICS_AND_ADMINISTRATION_LAW_AND_SECURITY_ACTS
        POLITICAL_AND_ADMINISTRATIVE_PERSONNEL = \
            MeaningCategory.POLITICS_AND_ADMINISTRATION_POLITICAL_AND_ADMINISTRATIVE_PERSONNEL

    class NATURE:
        """Helper class for nature meaning categories."""
        ALL = MeaningCategory.NATURE_ALL
        TOPOGRAPHY = MeaningCategory.NATURE_TOPOGRAPHY
        SURFACE_OBJECTS = MeaningCategory.NATURE_SURFACE_OBJECTS
        CELESTIAL_BODIES = MeaningCategory.NATURE_CELESTIAL_BODIES
        NATURAL_RESOURCES = MeaningCategory.NATURE_NATURAL_RESOURCES
        DISASTERS = MeaningCategory.NATURE_DISASTERS
        WEATHER_AND_CLIMATE = MeaningCategory.NATURE_WEATHER_AND_CLIMATE

    class ANIMALS_AND_PLANTS:
        """Helper class for animals and plants meaning categories."""
        ALL = MeaningCategory.ANIMALS_AND_PLANTS_ALL
        ANIMALS = MeaningCategory.ANIMALS_AND_PLANTS_ANIMALS
        INSECTS = MeaningCategory.ANIMALS_AND_PLANTS_INSECTS
        PLANTS = MeaningCategory.ANIMALS_AND_PLANTS_PLANTS
        PARTS_OF_ANIMALS = MeaningCategory.ANIMALS_AND_PLANTS_PARTS_OF_ANIMALS
        PARTS_OF_PLANTS = MeaningCategory.ANIMALS_AND_PLANTS_PARTS_OF_PLANTS
        BEHAVIORS = MeaningCategory.ANIMALS_AND_PLANTS_BEHAVIORS
        SOUNDS = MeaningCategory.ANIMALS_AND_PLANTS_SOUNDS

    class CONCEPTS:
        """Helper class for concept meaning categories."""
        ALL = MeaningCategory.CONCEPTS_ALL
        SHAPE = MeaningCategory.CONCEPTS_SHAPE
        PROPERTY = MeaningCategory.CONCEPTS_PROPERTY
        SPEED = MeaningCategory.CONCEPTS_SPEED
        BRIGHTNESS = MeaningCategory.CONCEPTS_BRIGHTNESS
        TEMPERATURE = MeaningCategory.CONCEPTS_TEMPERATURE
        COLORS = MeaningCategory.CONCEPTS_COLORS
        NUMBERS = MeaningCategory.CONCEPTS_NUMBERS
        COUNTERS = MeaningCategory.CONCEPTS_COUNTERS
        AMOUNT = MeaningCategory.CONCEPTS_AMOUNT
        DEGREE = MeaningCategory.CONCEPTS_DEGREE
        ORDER = MeaningCategory.CONCEPTS_ORDER
        FREQUENCY = MeaningCategory.CONCEPTS_FREQUENCY
        TIME = MeaningCategory.CONCEPTS_TIME
        LOCATION_AND_DIRECTION = MeaningCategory.CONCEPTS_LOCATION_AND_DIRECTION
        AREA = MeaningCategory.CONCEPTS_AREA
        INSTRUCTIONS = MeaningCategory.CONCEPTS_INSTRUCTIONS
        CONNECTION = MeaningCategory.CONCEPTS_CONNECTION
        QUESTION_WORDS = MeaningCategory.CONCEPTS_QUESTION_WORDS
        PRONOUNS = MeaningCategory.CONCEPTS_PRONOUNS

class SubjectCategoryHelper:
    """Helper class for subject categories."""

    def __new__(cls, value):
        return SubjectCategory(value)

    @staticmethod
    def enum():
        """Returns the underlying enumeration type."""
        return SubjectCategory

    ALL = SubjectCategory.ALL

    class ELEMENTARY:
        """Helper class for elementary subject categories."""
        GREETING = SubjectCategory.ELEMENTARY_GREETING
        INTRODUCING_ONESELF = SubjectCategory.ELEMENTARY_INTRODUCING_ONESELF
        INTRODUCING_FAMILY = SubjectCategory.ELEMENTARY_INTRODUCING_FAMILY
        EXCHANGING_PERSONAL_INFORMATION = SubjectCategory.ELEMENTARY_EXCHANGING_PERSONAL_INFORMATION
        DESCRIBING_LOCATION = SubjectCategory.ELEMENTARY_DESCRIBING_LOCATION
        DIRECTIONS = SubjectCategory.ELEMENTARY_DIRECTIONS
        USING_TRANSPORTATION = SubjectCategory.ELEMENTARY_USING_TRANSPORTATION
        PURCHASING_GOODS = SubjectCategory.ELEMENTARY_PURCHASING_GOODS
        ORDERING_FOOD = SubjectCategory.ELEMENTARY_ORDERING_FOOD
        DESCRIBING_DISHES = SubjectCategory.ELEMENTARY_DESCRIBING_DISHES
        EXPRESSING_TIME = SubjectCategory.ELEMENTARY_EXPRESSING_TIME
        EXPRESSING_DATE = SubjectCategory.ELEMENTARY_EXPRESSING_DATE
        EXPRESSING_DAY_OF_THE_WEEK = SubjectCategory.ELEMENTARY_EXPRESSING_DAY_OF_THE_WEEK
        WEATHER_AND_SEASON = SubjectCategory.ELEMENTARY_WEATHER_AND_SEASON
        DAILY_LIFE = SubjectCategory.ELEMENTARY_DAILY_LIFE
        SCHOOL_LIFE = SubjectCategory.ELEMENTARY_SCHOOL_LIFE
        LIFE_IN_KOREA = SubjectCategory.ELEMENTARY_LIFE_IN_KOREA
        MAKING_PROMISES = SubjectCategory.ELEMENTARY_MAKING_PROMISES
        MAKING_PHONE_CALLS = SubjectCategory.ELEMENTARY_MAKING_PHONE_CALLS
        EXPRESSING_GRATITUDE = SubjectCategory.ELEMENTARY_EXPRESSING_GRATITUDE
        APOLOGIZING = SubjectCategory.ELEMENTARY_APOLOGIZING
        TRAVEL = SubjectCategory.ELEMENTARY_TRAVEL
        WEEKENDS_AND_HOLIDAYS = SubjectCategory.ELEMENTARY_WEEKENDS_AND_HOLIDAYS
        HOBBIES = SubjectCategory.ELEMENTARY_HOBBIES
        FAMILY_EVENTS = SubjectCategory.ELEMENTARY_FAMILY_EVENTS
        HEALTH = SubjectCategory.ELEMENTARY_HEALTH
        USING_THE_HOSPITAL = SubjectCategory.ELEMENTARY_USING_THE_HOSPITAL
        USING_THE_PHARMACY = SubjectCategory.ELEMENTARY_USING_THE_PHARMACY
        USING_THE_LIBRARY = SubjectCategory.ELEMENTARY_USING_THE_LIBRARY
        USING_THE_POST_OFFICE = SubjectCategory.ELEMENTARY_USING_THE_POST_OFFICE
        USING_THE_IMMIGRATION_OFFICE = SubjectCategory.ELEMENTARY_USING_THE_IMMIGRATION_OFFICE
        INVITING_AND_VISITING = SubjectCategory.ELEMENTARY_INVITING_AND_VISITING
        FINDING_A_HOUSE = SubjectCategory.ELEMENTARY_FINDING_A_HOUSE
        HOUSEWORK = SubjectCategory.ELEMENTARY_HOUSEWORK
        EXPRESSING_EMOTIONS = SubjectCategory.ELEMENTARY_EXPRESSING_EMOTIONS
        DESCRIBING_PERSONALITY = SubjectCategory.ELEMENTARY_DESCRIBING_PERSONALITY
        DESCRIBING_CLOTHES = SubjectCategory.ELEMENTARY_DESCRIBING_CLOTHES
        DESCRIBING_PHYSICAL_FEATURES = SubjectCategory.ELEMENTARY_DESCRIBING_PHYSICAL_FEATURES
        WATCHING_MOVIES = SubjectCategory.ELEMENTARY_WATCHING_MOVIES

    class INTERMEDIATE:
        """Helper class for intermediate subject categories."""
        EXCHANGING_PERSONAL_INFORMATION = \
            SubjectCategory.INTERMEDIATE_EXCHANGING_PERSONAL_INFORMATION
        USING_TRANSPORTATION = SubjectCategory.INTERMEDIATE_USING_TRANSPORTATION
        GEOLOGICAL_INFORMATION = SubjectCategory.INTERMEDIATE_GEOLOGICAL_INFORMATION
        PURCHASING_GOODS = SubjectCategory.INTERMEDIATE_PURCHASING_GOODS
        DESCRIBING_FOOD = SubjectCategory.INTERMEDIATE_DESCRIBING_FOOD
        DESCRIBING_DISHES = SubjectCategory.INTERMEDIATE_DESCRIBING_DISHES
        WEATHER_AND_SEASON = SubjectCategory.INTERMEDIATE_WEATHER_AND_SEASON
        SCHOOL_LIFE = SubjectCategory.INTERMEDIATE_SCHOOL_LIFE
        LIFE_IN_KOREA = SubjectCategory.INTERMEDIATE_LIFE_IN_KOREA
        JOBS_AND_CAREERS = SubjectCategory.INTERMEDIATE_JOBS_AND_CAREERS
        WORKPLACE_LIFE = SubjectCategory.INTERMEDIATE_WORKPLACE_LIFE
        TRAVEL = SubjectCategory.INTERMEDIATE_TRAVEL
        WEEKENDS_AND_HOLIDAYS = SubjectCategory.INTERMEDIATE_WEEKENDS_AND_HOLIDAYS
        HOBBIES = SubjectCategory.INTERMEDIATE_HOBBIES
        FAMILY_EVENTS = SubjectCategory.INTERMEDIATE_FAMILY_EVENTS
        FAMILY_EVENTS_DURING_HOLIDAYS = SubjectCategory.INTERMEDIATE_FAMILY_EVENTS_DURING_HOLIDAYS
        HEALTH = SubjectCategory.INTERMEDIATE_HEALTH
        USING_PUBLIC_INSTITUTIONS = SubjectCategory.INTERMEDIATE_USING_PUBLIC_INSTITUTIONS
        INVITING_AND_VISITING = SubjectCategory.INTERMEDIATE_INVITING_AND_VISITING
        FINDING_A_HOUSE = SubjectCategory.INTERMEDIATE_FINDING_A_HOUSE
        HOUSEWORK = SubjectCategory.INTERMEDIATE_HOUSEWORK
        EXPRESSING_EMOTIONS = SubjectCategory.INTERMEDIATE_EXPRESSING_EMOTIONS
        DESCRIBING_PERSONALITY = SubjectCategory.INTERMEDIATE_DESCRIBING_PERSONALITY
        DESCRIBING_CLOTHES = SubjectCategory.INTERMEDIATE_DESCRIBING_CLOTHES
        DESCRIBING_PHYSICAL_FEATURES = SubjectCategory.INTERMEDIATE_DESCRIBING_PHYSICAL_FEATURES
        PERFORMANCES_AND_APPRECIATION = SubjectCategory.INTERMEDIATE_PERFORMANCES_AND_APPRECIATION
        MASS_MEDIA = SubjectCategory.INTERMEDIATE_MASS_MEDIA
        COMPUTERS_AND_THE_INTERNET = SubjectCategory.INTERMEDIATE_COMPUTERS_AND_THE_INTERNET
        DESCRIBING_EVENTS_AND_DISASTERS = \
            SubjectCategory.INTERMEDIATE_DESCRIBING_EVENTS_AND_DISASTERS
        ENVIRONMENTAL_ISSUES = SubjectCategory.INTERMEDIATE_ENVIRONMENTAL_ISSUES
        COMPARING_CULTURES = SubjectCategory.INTERMEDIATE_COMPARING_CULTURES
        HUMAN_RELATIONSHIPS = SubjectCategory.INTERMEDIATE_HUMAN_RELATIONSHIPS
        KOREAN_LITERATURE = SubjectCategory.INTERMEDIATE_KOREAN_LITERATURE
        SOLVING_PROBLEMS = SubjectCategory.INTERMEDIATE_SOLVING_PROBLEMS
        TALKING_ABOUT_MISTAKES = SubjectCategory.INTERMEDIATE_TALKING_ABOUT_MISTAKES
        DATING_AND_MARRIAGE = SubjectCategory.INTERMEDIATE_DATING_AND_MARRIAGE
        LANGUAGE = SubjectCategory.INTERMEDIATE_LANGUAGE

    class ADVANCED:
        """Helper class for advanced subject categories."""
        GEOLOGICAL_INFORMATION = SubjectCategory.ADVANCED_GEOLOGICAL_INFORMATION
        ECONOMICS_AND_ADMINISTRATION = SubjectCategory.ADVANCED_ECONOMICS_AND_ADMINISTRATION
        DIETARY_CULTURE = SubjectCategory.ADVANCED_DIETARY_CULTURE
        CLIMATE = SubjectCategory.ADVANCED_CLIMATE
        EDUCATION = SubjectCategory.ADVANCED_EDUCATION
        JOBS_AND_CAREERS = SubjectCategory.ADVANCED_JOBS_AND_CAREERS
        WORKPLACE_LIFE = SubjectCategory.ADVANCED_WORKPLACE_LIFE
        HOBBIES = SubjectCategory.ADVANCED_HOBBIES
        HEALTH_AND_MEDICAL_TREATMENT = SubjectCategory.ADVANCED_HEALTH_AND_MEDICAL_TREATMENT
        RESIDENTIAL_AREA = SubjectCategory.ADVANCED_RESIDENTIAL_AREA
        PSYCHOLOGY = SubjectCategory.ADVANCED_PSYCHOLOGY
        APPEARANCE = SubjectCategory.ADVANCED_APPEARANCE
        POP_CULTURE = SubjectCategory.ADVANCED_POP_CULTURE
        COMPUTERS_AND_THE_INTERNET = SubjectCategory.ADVANCED_COMPUTERS_AND_THE_INTERNET
        SOCIAL_ISSUES = SubjectCategory.ADVANCED_SOCIAL_ISSUES
        ENVIRONMENTAL_ISSUES = SubjectCategory.ADVANCED_ENVIRONMENTAL_ISSUES
        SOCIAL_SYSTEM = SubjectCategory.ADVANCED_SOCIAL_SYSTEM
        CULTURAL_DIFFERENCES = SubjectCategory.ADVANCED_CULTURAL_DIFFERENCES
        HUMAN_RELATIONSHIPS = SubjectCategory.ADVANCED_HUMAN_RELATIONSHIPS
        ART = SubjectCategory.ADVANCED_ART
        ARCHITECTURE = SubjectCategory.ADVANCED_ARCHITECTURE
        SCIENCE_AND_TECHNOLOGY = SubjectCategory.ADVANCED_SCIENCE_AND_TECHNOLOGY
        LAW = SubjectCategory.ADVANCED_LAW
        SPORTS = SubjectCategory.ADVANCED_SPORTS
        PRESS = SubjectCategory.ADVANCED_PRESS
        LANGUAGE = SubjectCategory.ADVANCED_LANGUAGE
        HISTORY = SubjectCategory.ADVANCED_HISTORY
        POLITICS = SubjectCategory.ADVANCED_POLITICS
        RELIGION = SubjectCategory.ADVANCED_RELIGION
        PHILOSOPHY_AND_ETHICS = SubjectCategory.ADVANCED_PHILOSOPHY_AND_ETHICS
