"""
Contains helper classes.
"""

# pylint: disable=invalid-name
# pylint: disable=too-few-public-methods

from enum import Enum


class MeaningCategory(Enum):
    """Enumeration class that contains meaning category values."""
    ALL = 0
    HUMAN_ALL = 1
    HUMAN_TYPES_OF_PEOPLE = 2
    HUMAN_BODY_PARTS = 3
    HUMAN_HEALTH_STATUS = 4
    HUMAN_PHYSIOLOGICAL_PHENOMENA = 5
    HUMAN_SENSES = 6
    HUMAN_EMOTION = 7
    HUMAN_PERSONALITY = 8
    HUMAN_ATTITUDE = 9
    HUMAN_FEATURES = 10
    HUMAN_ABILITY = 11
    HUMAN_PHYSICAL_CHANGES = 12
    HUMAN_PHYSICAL_ACTIVITIES = 13
    HUMAN_ACTIONS_DONE_TO_THE_BODY = 14
    HUMAN_COGNITIVE_BEHAVIOR = 15
    HUMAN_SOUND = 16
    HUMAN_INNER_PARTS_OF_THE_BODY = 17
    LIFE_ALL = 18
    LIFE_STATE_OF_BEING = 19
    LIFE_LIFE_ACTIVIES = 20
    LIFE_DAILY_ACTIVITIES = 21
    LIFE_KINSHIP = 22
    LIFE_FAMILY_EVENTS = 23
    LIFE_LEISURE_TOOLS = 24
    LIFE_LEISURE_FACILITIES = 25
    LIFE_LEISURE_ACTIVITIES = 26
    LIFE_DISEASES_AND_SYMPTOMS = 27
    LIFE_MEDICAL_ACTIVITIES = 28
    LIFE_MEDICAL_FACILITIES = 29
    LIFE_MEDICINE = 30
    DIETARY_ALL = 31
    DIETARY_FOOD_TYPES = 32
    DIETARY_VEGETABLES = 33
    DIETARY_GRAIN = 34
    DIETARY_FRUIT = 35
    DIETARY_BEVERAGES = 36
    DIETARY_FOOD_INGREDIENTS = 37
    DIETARY_COOKING_APPLIANCES = 38
    DIETARY_EATING_PLACES = 39
    DIETARY_TASTE = 40
    DIETARY_EATING_AND_COOKING_ACTIVITIES = 41
    CLOTHING_ALL = 42
    CLOTHING_TYPES_OF_CLOTHING = 43
    CLOTHING_FABRIC = 44
    CLOTHING_PARTS_OF_CLOTHING = 45
    CLOTHING_HATS_SHOES_ACCESSORIES = 46
    CLOTHING_PLACES_RELATED_TO_CLOTHING = 47
    CLOTHING_STATE_OF_CLOTHING = 48
    CLOTHING_ACTIVITIES_RELATED_TO_CLOTHING = 49
    CLOTHING_BEAUTY_AND_HEALTH = 50
    HOME_LIFE_ALL = 51
    HOME_LIFE_BUILDING_TYPES = 52
    HOME_LIFE_TYPE_OF_HOUSING = 53
    HOME_LIFE_RESIDENTIAL_AREA = 54
    HOME_LIFE_HOUSEHOLD_ITEMS = 55
    HOME_LIFE_HOUSING_STRUCTURE = 56
    HOME_LIFE_RESIDENTIAL_STATUS = 57
    HOME_LIFE_RESIDENTIAL_ACTIVITIES = 58
    HOME_LIFE_RESIDENTIAL_CHORES = 59
    SOCIAL_LIFE_ALL = 60
    SOCIAL_LIFE_HUMAN_RELATIONSHIPS = 61
    SOCIAL_LIFE_MEANS_OF_COMMUNICATION = 62
    SOCIAL_LIFE_MODES_OF_TRANSPORTATION = 63
    SOCIAL_LIFE_PLACES_FOR_TRANSPORTATION_USAGE = 64
    SOCIAL_LIFE_MEDIA = 65
    SOCIAL_LIFE_WORKPLACE = 66
    SOCIAL_LIFE_TITLES_AND_POSITIONS = 67
    SOCIAL_LIFE_OCCUPATION = 68
    SOCIAL_LIFE_SOCIAL_EVENTS = 69
    SOCIAL_LIFE_SOCIAL_LIFE_STATUS = 70
    SOCIAL_LIFE_SOCIAL_ACTIVITIES = 71
    SOCIAL_LIFE_TRANSPORTATION_USAGE = 72
    SOCIAL_LIFE_WORKPLACE_LIFE = 73
    SOCIAL_LIFE_LANGUAGE_ACTIVITIES = 74
    SOCIAL_LIFE_COMMUNICATION_ACTIVITIES = 75
    SOCIAL_LIFE_GRAMMAR_AND_SPEECH = 76
    ECONOMIC_ALL = 77
    ECONOMIC_PEOPLE = 78
    ECONOMIC_PLACES = 79
    ECONOMIC_MEANS = 80
    ECONOMIC_PRODUCTS = 81
    ECONOMIC_STATUS = 82
    ECONOMIC_ACTIVITIES = 83
    EDUCATION_ALL = 84
    EDUCATION_PEOPLE = 85
    EDUCATION_MAJORS_AND_SUBJECTS = 86
    EDUCATION_EDUCATIONAL_INSTITUTIONS = 87
    EDUCATION_SCHOOL_FACILITIES = 88
    EDUCATION_OBJECTS = 89
    EDUCATION_ACADEMIC_TERMS = 90
    EDUCATION_TEACHING_AND_LEARNING_ACTIVITIES = 91
    EDUCATION_ACADEMIC_ACTIVITIES = 92
    RELIGION_ALL = 93
    RELIGION_TYPES_OF_RELIGION = 94
    RELIGION_PLACES = 95
    RELIGION_PEOPLE = 96
    RELIGION_RELIGIOUS_WORDS = 97
    RELIGION_MAJOR_FIGURES = 98
    RELIGION_OBJECTS = 99
    RELIGION_PRACTICES = 100
    CULTURE_ALL = 101
    CULTURE_CULTURAL_ACTIVITY_PARTICIPANTS = 102
    CULTURE_MUSIC = 103
    CULTURE_FINE_ART = 104
    CULTURE_LITERATURE = 105
    CULTURE_ART = 106
    CULTURE_POP_CULTURE = 107
    CULTURE_TRADITIONAL_CULTURE = 108
    CULTURE_CULTURAL_ACTIVITY_PLACES = 109
    CULTURE_CULTURAL_ACTIVITIES = 110
    POLITICS_AND_ADMINISTRATION_ALL = 111
    POLITICS_AND_ADMINISTRATION_PUBLIC_INSTITUTIONS = 112
    POLITICS_AND_ADMINISTRATION_JUDICIAL_AND_SECURITY_PERSONNEL = 113
    POLITICS_AND_ADMINISTRATION_WEAPONS = 114
    POLITICS_AND_ADMINISTRATION_POLITICS_AND_SECURITY = 115
    POLITICS_AND_ADMINISTRATION_POLITICAL_ACTS = 116
    POLITICS_AND_ADMINISTRATION_LAW_AND_SECURITY_ACTS = 117
    POLITICS_AND_ADMINISTRATION_POLITICAL_AND_ADMINISTRATIVE_PERSONNEL = 118
    NATURE_ALL = 119
    NATURE_TOPOGRAPHY = 120
    NATURE_SURFACE_OBJECTS = 121
    NATURE_CELESTIAL_BODIES = 122
    NATURE_NATURAL_RESOURCES = 123
    NATURE_DISASTERS = 124
    NATURE_WEATHER_AND_CLIMATE = 125
    ANIMALS_AND_PLANTS_ALL = 126
    ANIMALS_AND_PLANTS_ANIMALS = 127
    ANIMALS_AND_PLANTS_INSECTS = 128
    ANIMALS_AND_PLANTS_PLANTS = 129
    ANIMALS_AND_PLANTS_PARTS_OF_ANIMALS = 130
    ANIMALS_AND_PLANTS_PARTS_OF_PLANTS = 131
    ANIMALS_AND_PLANTS_BEHAVIORS = 132
    ANIMALS_AND_PLANTS_SOUNDS = 133
    CONCEPTS_ALL = 134
    CONCEPTS_SHAPE = 135
    CONCEPTS_PROPERTY = 136
    CONCEPTS_SPEED = 137
    CONCEPTS_BRIGHTNESS = 138
    CONCEPTS_TEMPERATURE = 139
    CONCEPTS_COLORS = 140
    CONCEPTS_NUMBERS = 141
    CONCEPTS_COUNTERS = 142
    CONCEPTS_AMOUNT = 143
    CONCEPTS_DEGREE = 144
    CONCEPTS_ORDER = 145
    CONCEPTS_FREQUENCY = 146
    CONCEPTS_TIME = 147
    CONCEPTS_LOCATION_AND_DIRECTION = 148
    CONCEPTS_AREA = 149
    CONCEPTS_INSTRUCTIONS = 150
    CONCEPTS_CONNECTION = 151
    CONCEPTS_QUESTION_WORDS = 152
    CONCEPTS_PRONOUNS = 153

class MeaningCategoryHelper:
    """Helper class for meaning categories."""

    def __new__(cls, value):
        return MeaningCategory(value)

    @staticmethod
    def enum():
        """Returns the underlying enumeration type."""
        return MeaningCategory

    ALL = MeaningCategory.ALL

    class HUMAN:
        """Helper class for human meaning categories."""
        ALL = MeaningCategory.HUMAN_ALL
        TYPES_OF_PEOPLE = MeaningCategory.HUMAN_TYPES_OF_PEOPLE
        BODY_PARTS = MeaningCategory.HUMAN_BODY_PARTS
        HEALTH_STATUS = MeaningCategory.HUMAN_HEALTH_STATUS
        PHYSIOLOGICAL_PHENOMENA = MeaningCategory.HUMAN_PHYSIOLOGICAL_PHENOMENA
        SENSES = MeaningCategory.HUMAN_SENSES
        EMOTION = MeaningCategory.HUMAN_EMOTION
        PERSONALITY = MeaningCategory.HUMAN_PERSONALITY
        ATTITUDE = MeaningCategory.HUMAN_ATTITUDE
        FEATURES = MeaningCategory.HUMAN_FEATURES
        ABILITY = MeaningCategory.HUMAN_ABILITY
        PHYSICAL_CHANGES = MeaningCategory.HUMAN_PHYSICAL_CHANGES
        PHYSICAL_ACTIVITIES = MeaningCategory.HUMAN_PHYSICAL_ACTIVITIES
        ACTIONS_DONE_TO_THE_BODY = MeaningCategory.HUMAN_ACTIONS_DONE_TO_THE_BODY
        COGNITIVE_BEHAVIOR = MeaningCategory.HUMAN_COGNITIVE_BEHAVIOR
        SOUND = MeaningCategory.HUMAN_SOUND
        INNER_PARTS_OF_THE_BODY = MeaningCategory.HUMAN_INNER_PARTS_OF_THE_BODY

    class LIFE:
        """Helper class for life meaning categories."""
        ALL = MeaningCategory.LIFE_ALL
        STATE_OF_BEING = MeaningCategory.LIFE_STATE_OF_BEING
        LIFE_ACTIVIES = MeaningCategory.LIFE_LIFE_ACTIVIES
        DAILY_ACTIVITIES = MeaningCategory.LIFE_DAILY_ACTIVITIES
        KINSHIP = MeaningCategory.LIFE_KINSHIP
        FAMILY_EVENTS = MeaningCategory.LIFE_FAMILY_EVENTS
        LEISURE_TOOLS = MeaningCategory.LIFE_LEISURE_TOOLS
        LEISURE_FACILITIES = MeaningCategory.LIFE_LEISURE_FACILITIES
        LEISURE_ACTIVITIES = MeaningCategory.LIFE_LEISURE_ACTIVITIES
        DISEASES_AND_SYMPTOMS = MeaningCategory.LIFE_DISEASES_AND_SYMPTOMS
        MEDICAL_ACTIVITIES = MeaningCategory.LIFE_MEDICAL_ACTIVITIES
        MEDICAL_FACILITIES = MeaningCategory.LIFE_MEDICAL_FACILITIES
        MEDICINE = MeaningCategory.LIFE_MEDICINE

    class DIETARY:
        """Helper class for dietary meaning categories."""
        ALL = MeaningCategory.DIETARY_ALL
        FOOD_TYPES = MeaningCategory.DIETARY_FOOD_TYPES
        VEGETABLES = MeaningCategory.DIETARY_VEGETABLES
        GRAIN = MeaningCategory.DIETARY_GRAIN
        FRUIT = MeaningCategory.DIETARY_FRUIT
        BEVERAGES = MeaningCategory.DIETARY_BEVERAGES
        FOOD_INGREDIENTS = MeaningCategory.DIETARY_FOOD_INGREDIENTS
        COOKING_APPLIANCES = MeaningCategory.DIETARY_COOKING_APPLIANCES
        EATING_PLACES = MeaningCategory.DIETARY_EATING_PLACES
        TASTE = MeaningCategory.DIETARY_TASTE
        EATING_AND_COOKING_ACTIVITIES = MeaningCategory.DIETARY_EATING_AND_COOKING_ACTIVITIES

    class CLOTHING:
        """Helper class for clothing meaning categories."""
        ALL = MeaningCategory.CLOTHING_ALL
        TYPES_OF_CLOTHING = MeaningCategory.CLOTHING_TYPES_OF_CLOTHING
        FABRIC = MeaningCategory.CLOTHING_FABRIC
        PARTS_OF_CLOTHING = MeaningCategory.CLOTHING_PARTS_OF_CLOTHING
        HATS_SHOES_ACCESSORIES = MeaningCategory.CLOTHING_HATS_SHOES_ACCESSORIES
        PLACES_RELATED_TO_CLOTHING = MeaningCategory.CLOTHING_PLACES_RELATED_TO_CLOTHING
        STATE_OF_CLOTHING = MeaningCategory.CLOTHING_STATE_OF_CLOTHING
        ACTIVITIES_RELATED_TO_CLOTHING = MeaningCategory.CLOTHING_ACTIVITIES_RELATED_TO_CLOTHING
        BEAUTY_AND_HEALTH = MeaningCategory.CLOTHING_BEAUTY_AND_HEALTH

    class HOME_LIFE:
        """Helper class for home life meaning categories."""
        ALL = MeaningCategory.HOME_LIFE_ALL
        BUILDING_TYPES = MeaningCategory.HOME_LIFE_BUILDING_TYPES
        TYPE_OF_HOUSING = MeaningCategory.HOME_LIFE_TYPE_OF_HOUSING
        RESIDENTIAL_AREA = MeaningCategory.HOME_LIFE_RESIDENTIAL_AREA
        HOUSEHOLD_ITEMS = MeaningCategory.HOME_LIFE_HOUSEHOLD_ITEMS
        HOUSING_STRUCTURE = MeaningCategory.HOME_LIFE_HOUSING_STRUCTURE
        RESIDENTIAL_STATUS = MeaningCategory.HOME_LIFE_RESIDENTIAL_STATUS
        RESIDENTIAL_ACTIVITIES = MeaningCategory.HOME_LIFE_RESIDENTIAL_ACTIVITIES
        RESIDENTIAL_CHORES = MeaningCategory.HOME_LIFE_RESIDENTIAL_CHORES

    class SOCIAL_LIFE:
        """Helper class for social life meaning categories."""
        ALL = MeaningCategory.SOCIAL_LIFE_ALL
        HUMAN_RELATIONSHIPS = MeaningCategory.SOCIAL_LIFE_HUMAN_RELATIONSHIPS
        MEANS_OF_COMMUNICATION = MeaningCategory.SOCIAL_LIFE_MEANS_OF_COMMUNICATION
        MODES_OF_TRANSPORTATION = MeaningCategory.SOCIAL_LIFE_MODES_OF_TRANSPORTATION
        PLACES_FOR_TRANSPORTATION_USAGE = \
            MeaningCategory.SOCIAL_LIFE_PLACES_FOR_TRANSPORTATION_USAGE
        MEDIA = MeaningCategory.SOCIAL_LIFE_MEDIA
        WORKPLACE = MeaningCategory.SOCIAL_LIFE_WORKPLACE
        TITLES_AND_POSITIONS = MeaningCategory.SOCIAL_LIFE_TITLES_AND_POSITIONS
        OCCUPATION = MeaningCategory.SOCIAL_LIFE_OCCUPATION
        SOCIAL_EVENTS = MeaningCategory.SOCIAL_LIFE_SOCIAL_EVENTS
        SOCIAL_LIFE_STATUS = MeaningCategory.SOCIAL_LIFE_SOCIAL_LIFE_STATUS
        SOCIAL_ACTIVITIES = MeaningCategory.SOCIAL_LIFE_SOCIAL_ACTIVITIES
        TRANSPORTATION_USAGE = MeaningCategory.SOCIAL_LIFE_TRANSPORTATION_USAGE
        WORKPLACE_LIFE = MeaningCategory.SOCIAL_LIFE_WORKPLACE_LIFE
        LANGUAGE_ACTIVITIES = MeaningCategory.SOCIAL_LIFE_LANGUAGE_ACTIVITIES
        COMMUNICATION_ACTIVITIES = MeaningCategory.SOCIAL_LIFE_COMMUNICATION_ACTIVITIES
        GRAMMAR_AND_SPEECH = MeaningCategory.SOCIAL_LIFE_GRAMMAR_AND_SPEECH

    class ECONOMIC:
        """Helper class for economic meaning categories."""
        ALL = MeaningCategory.ECONOMIC_ALL
        PEOPLE = MeaningCategory.ECONOMIC_PEOPLE
        PLACES = MeaningCategory.ECONOMIC_PLACES
        MEANS = MeaningCategory.ECONOMIC_MEANS
        PRODUCTS = MeaningCategory.ECONOMIC_PRODUCTS
        STATUS = MeaningCategory.ECONOMIC_STATUS
        ACTIVITIES = MeaningCategory.ECONOMIC_ACTIVITIES

    class EDUCATION:
        """Helper class for education meaning categories."""
        ALL = MeaningCategory.EDUCATION_ALL
        PEOPLE = MeaningCategory.EDUCATION_PEOPLE
        MAJORS_AND_SUBJECTS = MeaningCategory.EDUCATION_MAJORS_AND_SUBJECTS
        EDUCATIONAL_INSTITUTIONS = MeaningCategory.EDUCATION_EDUCATIONAL_INSTITUTIONS
        SCHOOL_FACILITIES = MeaningCategory.EDUCATION_SCHOOL_FACILITIES
        OBJECTS = MeaningCategory.EDUCATION_OBJECTS
        ACADEMIC_TERMS = MeaningCategory.EDUCATION_ACADEMIC_TERMS
        TEACHING_AND_LEARNING_ACTIVITIES = \
            MeaningCategory.EDUCATION_TEACHING_AND_LEARNING_ACTIVITIES
        ACADEMIC_ACTIVITIES = MeaningCategory.EDUCATION_ACADEMIC_ACTIVITIES

    class RELIGION:
        """Helper class for religion meaning categories."""
        ALL = MeaningCategory.RELIGION_ALL
        TYPES_OF_RELIGION = MeaningCategory.RELIGION_TYPES_OF_RELIGION
        PLACES = MeaningCategory.RELIGION_PLACES
        PEOPLE = MeaningCategory.RELIGION_PEOPLE
        RELIGIOUS_WORDS = MeaningCategory.RELIGION_RELIGIOUS_WORDS
        MAJOR_FIGURES = MeaningCategory.RELIGION_MAJOR_FIGURES
        OBJECTS = MeaningCategory.RELIGION_OBJECTS
        PRACTICES = MeaningCategory.RELIGION_PRACTICES

    class CULTURE:
        """Helper class for culture meaning categories."""
        ALL = MeaningCategory.CULTURE_ALL
        CULTURAL_ACTIVITY_PARTICIPANTS = MeaningCategory.CULTURE_CULTURAL_ACTIVITY_PARTICIPANTS
        MUSIC = MeaningCategory.CULTURE_MUSIC
        FINE_ART = MeaningCategory.CULTURE_FINE_ART
        LITERATURE = MeaningCategory.CULTURE_LITERATURE
        ART = MeaningCategory.CULTURE_ART
        POP_CULTURE = MeaningCategory.CULTURE_POP_CULTURE
        TRADITIONAL_CULTURE = MeaningCategory.CULTURE_TRADITIONAL_CULTURE
        CULTURAL_ACTIVITY_PLACES = MeaningCategory.CULTURE_CULTURAL_ACTIVITY_PLACES
        CULTURAL_ACTIVITIES = MeaningCategory.CULTURE_CULTURAL_ACTIVITIES

    class POLITICS_AND_ADMINISTRATION:
        """Helper class for politics and administration meaning categories."""
        ALL = MeaningCategory.POLITICS_AND_ADMINISTRATION_ALL
        PUBLIC_INSTITUTIONS = MeaningCategory.POLITICS_AND_ADMINISTRATION_PUBLIC_INSTITUTIONS
        JUDICIAL_AND_SECURITY_PERSONNEL = \
            MeaningCategory.POLITICS_AND_ADMINISTRATION_JUDICIAL_AND_SECURITY_PERSONNEL
        WEAPONS = MeaningCategory.POLITICS_AND_ADMINISTRATION_WEAPONS
        POLITICS_AND_SECURITY = MeaningCategory.POLITICS_AND_ADMINISTRATION_POLITICS_AND_SECURITY
        POLITICAL_ACTS = MeaningCategory.POLITICS_AND_ADMINISTRATION_POLITICAL_ACTS
        LAW_AND_SECURITY_ACTS = MeaningCategory.POLITICS_AND_ADMINISTRATION_LAW_AND_SECURITY_ACTS
        POLITICAL_AND_ADMINISTRATIVE_PERSONNEL = \
            MeaningCategory.POLITICS_AND_ADMINISTRATION_POLITICAL_AND_ADMINISTRATIVE_PERSONNEL

    class NATURE:
        """Helper class for nature meaning categories."""
        ALL = MeaningCategory.NATURE_ALL
        TOPOGRAPHY = MeaningCategory.NATURE_TOPOGRAPHY
        SURFACE_OBJECTS = MeaningCategory.NATURE_SURFACE_OBJECTS
        CELESTIAL_BODIES = MeaningCategory.NATURE_CELESTIAL_BODIES
        NATURAL_RESOURCES = MeaningCategory.NATURE_NATURAL_RESOURCES
        DISASTERS = MeaningCategory.NATURE_DISASTERS
        WEATHER_AND_CLIMATE = MeaningCategory.NATURE_WEATHER_AND_CLIMATE

    class ANIMALS_AND_PLANTS:
        """Helper class for animals and plants meaning categories."""
        ALL = MeaningCategory.ANIMALS_AND_PLANTS_ALL
        ANIMALS = MeaningCategory.ANIMALS_AND_PLANTS_ANIMALS
        INSECTS = MeaningCategory.ANIMALS_AND_PLANTS_INSECTS
        PLANTS = MeaningCategory.ANIMALS_AND_PLANTS_PLANTS
        PARTS_OF_ANIMALS = MeaningCategory.ANIMALS_AND_PLANTS_PARTS_OF_ANIMALS
        PARTS_OF_PLANTS = MeaningCategory.ANIMALS_AND_PLANTS_PARTS_OF_PLANTS
        BEHAVIORS = MeaningCategory.ANIMALS_AND_PLANTS_BEHAVIORS
        SOUNDS = MeaningCategory.ANIMALS_AND_PLANTS_SOUNDS

    class CONCEPTS:
        """Helper class for concept meaning categories."""
        ALL = MeaningCategory.CONCEPTS_ALL
        SHAPE = MeaningCategory.CONCEPTS_SHAPE
        PROPERTY = MeaningCategory.CONCEPTS_PROPERTY
        SPEED = MeaningCategory.CONCEPTS_SPEED
        BRIGHTNESS = MeaningCategory.CONCEPTS_BRIGHTNESS
        TEMPERATURE = MeaningCategory.CONCEPTS_TEMPERATURE
        COLORS = MeaningCategory.CONCEPTS_COLORS
        NUMBERS = MeaningCategory.CONCEPTS_NUMBERS
        COUNTERS = MeaningCategory.CONCEPTS_COUNTERS
        AMOUNT = MeaningCategory.CONCEPTS_AMOUNT
        DEGREE = MeaningCategory.CONCEPTS_DEGREE
        ORDER = MeaningCategory.CONCEPTS_ORDER
        FREQUENCY = MeaningCategory.CONCEPTS_FREQUENCY
        TIME = MeaningCategory.CONCEPTS_TIME
        LOCATION_AND_DIRECTION = MeaningCategory.CONCEPTS_LOCATION_AND_DIRECTION
        AREA = MeaningCategory.CONCEPTS_AREA
        INSTRUCTIONS = MeaningCategory.CONCEPTS_INSTRUCTIONS
        CONNECTION = MeaningCategory.CONCEPTS_CONNECTION
        QUESTION_WORDS = MeaningCategory.CONCEPTS_QUESTION_WORDS
        PRONOUNS = MeaningCategory.CONCEPTS_PRONOUNS
